In [9]:
import requests
import pandas as pd
import json

In [20]:
url = "https://rest.coinapi.io/v1/exchanges?limit=1000"
apikey = "3DDA805E-5521-415B-9C67-0C08B3FECA5F"

In [21]:
R = requests.request("get", url, headers={
    "X-CoinAPI-Key": apikey
})

content = json.loads(R.content.decode("utf-8"))

In [22]:
pd.DataFrame(content)

,exchange_id,website,name,data_start,data_end,data_quote_start,data_quote_end,data_orderbook_start,data_orderbook_end,data_trade_start,data_trade_end,data_symbols_count,volume_1hrs_usd,volume_1day_usd,volume_1mth_usd,metric_id
0,BINANCE,https://www.binance.com/,Binance,2017-07-14,2022-12-24,2017-12-18T21:50:58.3910192Z,2022-12-24T00:00:00.0000000Z,2017-12-18T21:50:58.3910192Z,2022-12-24T00:00:00.0000000Z,2017-07-14T04:00:00.3760000Z,2022-12-24T00:00:00.0000000Z,2138,1.393903e+08,5.078868e+09,3.101767e+11,NaN
1,KRAKEN,https://www.kraken.com/,Kraken,2013-10-22,2022-12-24,2014-07-31T13:05:46.0000000Z,2022-12-24T00:00:00.0000000Z,2014-07-31T13:05:46.0000000Z,2022-12-24T00:00:00.0000000Z,2013-10-22T23:09:46.8630000Z,2022-12-24T00:00:00.0000000Z,778,2.081319e+06,2.841702e+08,1.802241e+10,NaN
2,COINBASE,https://pro.coinbase.com/,Coinbase Pro (GDAX),2015-01-14,2022-12-24,2015-05-17T00:51:32.6370000Z,2022-12-24T00:00:00.0000000Z,2015-05-17T00:51:32.6370000Z,2022-12-24T00:00:00.0000000Z,2015-01-14T16:07:05.0000000Z,2022-12-24T00:00:00.0000000Z,640,1.505108e+07,8.172162e+08,3.943534e+10,NaN
3,BITSTAMP,https://www.bitstamp.net/,Bitstamp Ltd.,2011-09-13,2022-12-24,2014-02-24T17:43:05.0000000Z,2022-12-24T00:00:00.0000000Z,2014-02-24T17:43:05.0000000Z,2022-12-24T00:00:00.0000000Z,2011-09-13T13:53:36.0000000Z,2022-12-24T00:00:00.0000000Z,193,2.208084e+06,5.645121e+07,3.953743e+09,NaN
4,GEMINI,https://gemini.com/,Gemini,2015-10-08,2022-12-24,2017-03-18T22:53:42.0948480Z,2022-12-24T00:00:00.0000000Z,2017-03-18T22:53:42.0948480Z,2022-12-24T00:00:00.0000000Z,2015-10-08T13:40:07.8010000Z,2022-12-24T00:00:00.0000000Z,154,1.470470e+05,1.053021e+07,7.141814e+08,"[AUCTION_COLLAR_PRICE, AUCTION_HIGHEST_BID, AU..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332,INDODAX,https://indodax.com/,Indodax,2019-04-05,2022-12-24,2019-04-08T15:18:02.1868547Z,2022-12-24T00:00:00.0000000Z,2019-04-08T15:18:02.1868547Z,2022-12-24T00:00:00.0000000Z,2019-04-05T01:28:39.0000000Z,2022-12-24T00:00:00.0000000Z,285,2.455734e+05,4.825527e+06,2.772133e+08,NaN
333,BITZ,https://www.bit-z.com/,Bit-Z,2018-03-25,2021-10-21,2018-09-09T12:57:17.9973117Z,2021-10-21T06:22:41.4784518Z,2018-09-09T12:57:17.9973117Z,2020-08-05T14:37:16.4116718Z,2018-03-25T07:00:01.0000000Z,2021-10-21T06:24:09.0000000Z,685,0.000000e+00,0.000000e+00,0.000000e+00,NaN
334,COINEX,https://www.coinex.com/,CoinEx,2019-10-01,2022-12-24,2019-10-01T15:06:43.9334939Z,2022-12-24T00:00:00.0000000Z,2019-10-01T15:06:43.9334939Z,2022-12-24T00:00:00.0000000Z,2019-10-01T15:06:46.0000000Z,2022-12-24T00:00:00.0000000Z,1996,1.440517e+06,3.021994e+07,1.356298e+09,NaN
335,WEXNZ,https://wex.nz/,WexNz,2017-12-22,2018-11-20,2017-12-24T13:03:42.9064646Z,2018-11-20T23:48:42.8822625Z,2017-12-24T13:03:42.9064646Z,2018-11-20T23:48:42.8822625Z,2017-12-22T07:31:16.0000000Z,2018-11-20T23:45:53.0000000Z,59,0.000000e+00,0.000000e+00,0.000000e+00,NaN
336,AAX,https://www.aax.com/,AAX,2020-04-24,2022-12-09,2020-04-24T00:00:00.0000000Z,2022-12-09T00:00:00.0000000Z,2020-05-05T00:00:00.2223057Z,2022-12-09T00:00:00.0000000Z,2020-04-24T00:00:00.0000000Z,2022-11-15T00:00:00.0000000Z,392,0.000000e+00,0.000000e+00,0.000000e+00,NaN